### ISSUE TITLE
Provide a link to a repo on github using this

### ISSUE THREAD

**Issue by tacman** [ebitkov/build-symfony#1]
Thanks for releasing this!  I'm new to github actions, and trying to figure out how to test Symfony bundles and Symfony-based applications, so this looks very promising.

Do you have any applications or bundles that are on github using this?  I'd like to see it in action and then copy to action to my repositories.

**Comment by ebitkov** [comment]
I currently have no public repository using this action.

But I will try to create a demo repo for you later.

**Comment by ebitkov** [comment]
Hey, sorry for my late response. I actually forgot about your request...

I looked into your question and decided to not create a new repository just to show off this action, because I feel there is no real need for it. 

A simple workflow file in your project could look like this:

```yaml
# .github/workflows/build-symfony.yaml

name: "Build Symfony"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Symfony
        uses: ebitkov/build-symfony@v1
          with: 
            # see README.md for possible inputs
```

The README of this project describes all available inputs. Anything not documented there is currently not possible. If you need a specific feature feel free to open a new issue.

If you want to see some runner logs, look into the "Actions" tab of this project. It tests itself by building the official Symfony Skeleton.

I'm using this action for multiple private projects, so I'm keeping it up to date with the features I personally use, but am open for feature request.

I hope this helps you. If you have any questions don't hesitate to respond. Otherwise please close this issue, if it answers your request.
